nl <- read_sav(here("data/raw-private/DPES_2017.sav")) %>%
  dplyr::select(trust = V322,
                wtac = V320,
                age = V011,
                gender = V010,
                education = V368,
                income = D008,
                income2 = D009,
                pid = S110,
                political_interest = V024,
                rile_selfplacement = V133,
                gov_performance = S171,
                satisfaction_democracy = V240,
                elites_dont_care_people = V321,
                elites_are_main_problem = V323,
                strong_leaders_bend_rules = V324,
                people_make_policy_decisions = V325,
                elites_care_rich_powerful = V326,
                will_of_people = V327,
                differences_elites_people = V328,
                represented_ordinary_people = V329,
                no_action_all_talk = V330,
                dont_care_my_region = V331,
                vote_choice = V163) %>%
  mutate(country = "The Netherlands",
         trust = as.factor(trust),
         trust = as.numeric(trust),
         trust = replace(trust, which(trust>993), NA),
         trust = recode(trust,
                        `1` = 5,
                        `2` = 4,
                        `4` = 2,
                        `5` = 1),
         wtac = as.factor(wtac),
         wtac = as.numeric(wtac),
         wtac = replace(wtac, which(wtac>993), NA),
         age = as.factor(age),
         age = as.character(age),
         age = as.numeric(age),
         age = (2020 - age),
         gender = as.factor(gender),
         gender = recode(gender, 
                         `1` = "Male",
                         `2` = "Female"),
         education = as.factor(education),
         education = as.numeric(education),
         education =  replace(education, which(education>8), NA),
         education = recode(education,
                            `1` = 2,
                            `2` = 3,
                            `3` = 4,
                            `4` = 3,
                            `5` = 4,
                            `6` = 7,
                            `7` = 7),
         income2 = as.factor(income2),
         income2 = as.numeric(income2),
         income2 = replace(income2, which(income2==999999), NA),
         income2 = round(income2/max(income2),2),
         income2 = recode(income2, ifelse(income2<.2, 1,
                                          ifelse(income2>.2 & income2<.4,2,
                                                 ifelse(income2>.4 & income2<.6, 3,
                                                        ifelse(income2>.6 & income2<.8, 4, 5))))),
         income = as.factor(income),
         income = as.numeric(income),
         pid = as.factor(pid),
         pid = as.numeric(pid),
         pid = recode(pid,
                      `1` = "No Partisan ID",
                      `2` = "Partisan ID"),
         political_interest = as.factor(political_interest),
         political_interest = as.numeric(political_interest),
         political_interest = replace(political_interest, 
                                      which(political_interest>5), NA),
         political_interest = recode(political_interest,
                                     `1` = "Interested",
                                     `2` = "Interested",
                                     `3` = "Not Interested"),
         rile_selfplacement = as.factor(rile_selfplacement),
         rile_selfplacement = as.numeric(rile_selfplacement),
         gov_performance = as.factor(gov_performance),
         gov_performance = as.numeric(gov_performance),
         gov_performance = recode(gov_performance,
                                  `1` = "Satisfied",
                                  `2` = "Satisfied",
                                  `3` = "Satisfied",
                                  `4` = "Dissatisfied",
                                  `5` = "Dissatisfied"),
         satisfaction_democracy = as.factor(satisfaction_democracy),
         satisfaction_democracy = as.numeric(satisfaction_democracy),
         satisfaction_democracy = replace(satisfaction_democracy,
                                          which(satisfaction_democracy>5), NA),
         satisfaction_democracy = recode(satisfaction_democracy,
                                         `1` = "Satisfied",
                                         `2` = "Satisfied",
                                         `3` = "Dissatisfied",
                                         `4` = "Dissatisfied"),
         elites_dont_care_people = as.factor(elites_dont_care_people),
         elites_dont_care_people = as.numeric(elites_dont_care_people),
         elites_are_main_problem = as.factor(elites_are_main_problem),
         elites_are_main_problem = as.numeric(elites_are_main_problem),
         strong_leaders_bend_rules = as.factor(strong_leaders_bend_rules),
         strong_leaders_bend_rules = as.numeric(strong_leaders_bend_rules),
         people_make_policy_decisions = as.factor(people_make_policy_decisions),
         people_make_policy_decisions = as.numeric(people_make_policy_decisions),
         elites_care_rich_powerful = as.factor(elites_care_rich_powerful),
         elites_care_rich_powerful = as.numeric(elites_care_rich_powerful),
         will_of_people = as.factor(will_of_people),
         will_of_people = as.numeric(will_of_people),
         differences_elites_people = as.factor(differences_elites_people),
         differences_elites_people = as.numeric(differences_elites_people),
         represented_ordinary_people = as.factor(represented_ordinary_people),
         represented_ordinary_people = as.numeric(represented_ordinary_people),
         no_action_all_talk = as.factor(no_action_all_talk),
         no_action_all_talk = as.numeric(no_action_all_talk),
         dont_care_my_region = as.factor(dont_care_my_region),
         dont_care_my_region = as.numeric(dont_care_my_region),
         vote_choice = as.factor(vote_choice),
         vote_choice = as.character(vote_choice)) 

nl$income[which(is.na(nl$income))] <- nl$income2[which(is.na(nl$income))]
nl <- nl %>%
  dplyr::select(country, trust, wtac, age, gender, education, income, pid,
                political_interest,rile_selfplacement, gov_performance,
                satisfaction_democracy, elites_dont_care_people, 
                elites_are_main_problem, strong_leaders_bend_rules,
                people_make_policy_decisions, elites_care_rich_powerful, 
                will_of_people, differences_elites_people, 
                represented_ordinary_people, no_action_all_talk, 
                dont_care_my_region, vote_choice)
