uk <- readRDS("../../data/raw-private/bes.RDS") %>%
  dplyr::select(trust = q2_cses_4,
                wtac = q2_cses_2,
                age = q25_cses,
                gender = q24_cses,
                education,
                income = y01,
                pid = d02,
                political_interest = a03,
                rile_selfplacement = e01,
                gov_performance = q6_cses,
                satisfaction_democracy = m01,
                elites_dont_care_people = q2_cses_3,
                elites_are_main_problem = q2_cses_5,
                strong_leaders_bend_rules = q2_cses_6, #reversed!
                people_make_policy_decisions = q2_cses_7,
                elites_care_rich_powerful = q2_cses_8,
                vote_choice = b02) %>%
  mutate(country = "Great Britain",
         trust = as.numeric(trust),
         trust = replace(trust, which(trust<3), NA),
         trust = recode(trust,
                        `3` = 5,
                        `4` = 4,
                        `5` = 3,
                        `6` = 2,
                        `7` = 1),
         wtac = as.numeric(wtac),
         wtac = replace(wtac, which(wtac<3), NA),
         age = replace(age, which(age==-999), NA),
         gender = as.numeric(gender),
         gender = replace(gender, which(gender==1), NA),
         gender = recode(gender, 
                         `2` = "Male",
                         `3` = "Female"),
         education = as.numeric(education),
         education = recode(education,
                            `2` = 96,
                            `3` = 0,
                            `4` = 8,
                            `5` = 7,
                            `6` = 7,
                            `7` = 6,
                            `8` = 6,
                            `9` = 5,
                            `10` = 4,
                            `11` = 4,
                            `12` = 3,
                            `13` = 4,
                            `14` = 3,
                            `15` = 3,
                            `16` = 5,
                            `17` = 5,
                            `18` = 6,
                            `19` = 5,
                            `21` = 6,
                            `22` = 7,
                            `23` = 6),
         education =  replace(education, which(education==96), NA),
         income = as.numeric(income),
         income = recode(income,
                         `2` = 6,
                         `3` = 7,
                         `4` = 1,
                         `5` = 1,
                         `6` = 1,
                         `7` = 2,
                         `8` = 2,
                         `9` = 2,
                         `10` = 3,
                         `11` = 3,
                         `12` = 3,
                         `13` = 4,
                         `14` = 4,
                         `15` = 4,
                         `16` = 5,
                         `17` = 5,
                         `18` = 5),
         income = replace(income, which(income>5), NA),
         pid = as.numeric(pid),
         pid = replace(pid, which(pid<4), NA),
         pid = recode(pid,
                      `5` = "No Partisan ID",
                      `4` = "Partisan ID"),
         political_interest = as.numeric(political_interest),
         political_interest = replace(political_interest, 
                                      which(political_interest<3), NA),
         political_interest = recode(political_interest,
                                     `3` = "Interested",
                                     `4` = "Interested",
                                     `5` = "Not Interested",
                                     `6` = "Not Interested"),
         rile_selfplacement = as.numeric(rile_selfplacement),
         rile_selfplacement = replace(rile_selfplacement, 
                                      which(rile_selfplacement<4), NA),
         rile_selfplacement = rile_selfplacement - 4,
         gov_performance = as.numeric(gov_performance),
         gov_performance = replace(gov_performance,
                                   which(gov_performance<3), NA),
         gov_performance = recode(gov_performance,
                                  `3` = "Satisfied",
                                  `4` = "Satisfied",
                                  `5` = "Dissatisfied",
                                  `6` = "Dissatisfied"),
         satisfaction_democracy = as.numeric(satisfaction_democracy),
         satisfaction_democracy = replace(satisfaction_democracy,
                                          which(satisfaction_democracy<3), NA),
         satisfaction_democracy = recode(satisfaction_democracy,
                                         `3` = "Satisfied",
                                         `4` = "Satisfied",
                                         `5` = "Dissatisfied",
                                         `6` = "Dissatisfied"),
         elites_dont_care_people = as.numeric(elites_dont_care_people),
         elites_dont_care_people = replace(elites_dont_care_people,
                                           which(elites_dont_care_people<3), NA),
         elites_dont_care_people = elites_dont_care_people - 2,
         elites_are_main_problem = as.numeric(elites_are_main_problem),
         elites_are_main_problem = replace(elites_are_main_problem,
                                           which(elites_are_main_problem<3), NA),
         elites_are_main_problem = elites_are_main_problem - 2,
         strong_leaders_bend_rules = as.numeric(strong_leaders_bend_rules),
         strong_leaders_bend_rules = replace(strong_leaders_bend_rules,
                                             which(strong_leaders_bend_rules<3), NA),
         strong_leaders_bend_rules = recode(strong_leaders_bend_rules,
                                            `3` = 5,
                                            `4` = 4,
                                            `5` = 3,
                                            `6` = 2,
                                            `7` = 1),
         people_make_policy_decisions = as.numeric(people_make_policy_decisions),
         people_make_policy_decisions = replace(people_make_policy_decisions,
                                                which(people_make_policy_decisions<3), NA),
         people_make_policy_decisions = people_make_policy_decisions - 2,
         elites_care_rich_powerful = as.numeric(elites_care_rich_powerful),
         elites_care_rich_powerful = replace(elites_care_rich_powerful,
                                             which(elites_care_rich_powerful<3), NA),
         elites_care_rich_powerful = elites_care_rich_powerful - 2,
         will_of_people = NA,
         differences_elites_people = NA,
         represented_ordinary_people = NA,
         no_action_all_talk = NA,
         dont_care_my_region = NA,
         vote_choice = as.character(vote_choice)) %>%
  dplyr::select(country, trust, wtac, age, gender, education, income, pid, 
                political_interest, gov_performance,rile_selfplacement,
                satisfaction_democracy, elites_dont_care_people, 
                elites_are_main_problem, strong_leaders_bend_rules,
                people_make_policy_decisions,  elites_care_rich_powerful,
                will_of_people, differences_elites_people, 
                represented_ordinary_people, no_action_all_talk,
                dont_care_my_region, vote_choice)