d <- readRDS("../../data/raw-private/cses.rds") %>%
  filter(E1003 == 04002017 | E1003 == 25002017 |
           E1003 == 27602017 | E1003 == 38002018) %>%
  dplyr::select(country = E1003,
                trust = E3004_3,
                wtac = E3004_1,
                age = E2001_Y,
                gender = E2002,
                education = E2003,
                income = E2010,
                pid = E3024_1,
                political_interest = E3001,
                rile_selfplacement = E3020,
                gov_performance = E3009,
                satisfaction_democracy = E3023,
                elites_dont_care_people = E3004_2,
                elites_are_main_problem = E3004_4,
                strong_leaders_bend_rules = E3004_5,
                people_make_policy_decisions = E3004_6,
                elites_care_rich_powerful = E3004_7,
                vote_choice = E3013_LH_PL) %>%
  mutate(country = recode(country,
                          `04002017` = "Austria",
                          `25002017` = "France",
                          `27602017` = "Germany",
                          `38002018` = "Italy"),
         age = replace(age, which(age>9996), NA),
         age = 2020-age,
         gender = recode(gender, 
                         `1` = "Male", 
                         `2` = "Female"),
         education = recode(education, 
                            `96` = 0),
         education = replace(education, 
                             which(education>96), NA),
         income = replace(income, which(income>5), NA),
         pid = replace(pid, which(pid>5), NA),
         pid = recode(pid,
                      `0` = "No Partisan ID",
                      `1` = "Partisan ID"),
         political_interest = replace(political_interest, 
                                      which(political_interest>5), NA),
         political_interest = recode(political_interest,
                                     `1` = "Interested",
                                     `2` = "Interested",
                                     `3` = "Not Interested",
                                     `4` = "Not Interested"),
         gov_performance = replace(gov_performance, 
                                   which(gov_performance>5),NA),
         gov_performance = recode(gov_performance,
                                  `1` = "Satisfied",
                                  `2` = "Satisfied",
                                  `3` = "Dissatisfied",
                                  `4` = "Dissatisfied"),
         rile_selfplacement = replace(rile_selfplacement, 
                                      which(rile_selfplacement>10), NA),
         satisfaction_democracy = replace(satisfaction_democracy,
                                          which(satisfaction_democracy>5), NA),
         satisfaction_democracy = recode(satisfaction_democracy,
                                         `1` = "Satisfied",
                                         `2` = "Satisfied",
                                         `4` = "Dissatisfied",
                                         `5` = "Dissatisfied"),
         trust = replace(trust, which(trust>5), NA),
         trust = recode(trust,
                        `1` = 5,
                        `2` = 4,
                        `4` = 2,
                        `5` = 1),
         wtac = replace(wtac, which(wtac>5), NA),
         elites_dont_care_people = replace(elites_dont_care_people, 
                                           which(elites_dont_care_people>5), NA),
         elites_are_main_problem = replace(elites_are_main_problem,
                                           which(elites_are_main_problem>5), NA),
         strong_leaders_bend_rules = replace(strong_leaders_bend_rules,
                                             which(strong_leaders_bend_rules>5), NA),
         people_make_policy_decisions = replace(people_make_policy_decisions, 
                                                which(people_make_policy_decisions>5), NA),
         elites_care_rich_powerful = replace(elites_care_rich_powerful,
                                             which(elites_care_rich_powerful>5), NA),
         will_of_people = NA,
         differences_elites_people = NA,
         represented_ordinary_people = NA,
         no_action_all_talk = NA,
         dont_care_my_region = NA,
         vote_choice = as.character(vote_choice)) 