load(here("data/raw-private/cses5.rdata"))
d <- cses5 %>% 
  mutate(age = 2022 - as.numeric(E2001_Y),
         year = ifelse(E1004 == "BELF2019", 2019,
                ifelse(E1004 == "BELW2019", 2019,
                        unlist(map(strsplit(E1004, split = "_"), 2)))),
         country = ifelse(E1004 == "BELF2019", "BELF",
                   ifelse(E1004 == "BELW2019", "BELW",
                                 unlist(map(strsplit(E1004, split = "_"), 1))))) %>% 
  select(id = E1005, country, year,
         trust = E3004_3,
         swd = E3023,
         wtac = E3004_1,
         age,
         gender = E2002,
         education = E2003,
         income = E2010,
         pid = E3024_1,
         political_interest = E3001,
         rile_selfplacement = E3020,
         gov_performance = E3009) %>% 
  mutate(trust = ifelse(trust>5, NA, trust),
         trust = 6 - trust,
         swd = ifelse(swd>5, NA, swd),
         swd = recode(swd,
                                         `1` = 1,
                                         `2` = 1,
                                         `4` = 0,
                                         `5` = 0),
         wtac = ifelse(wtac>5, NA, wtac),
         age = ifelse(age<20, NA, age),
         gender = ifelse(gender>2, NA, gender), #1 = Male
         education = ifelse(education>9, NA, education),
         income = ifelse(income>5, NA, income),
         pid = ifelse(pid>1, NA, pid),
         political_interest = ifelse(political_interest>4, NA, political_interest),
         rile_selfplacement = ifelse(rile_selfplacement>10, NA, rile_selfplacement),
         gov_performance = ifelse(gov_performance>4, NA, gov_performance),
         country = recode(country,
                          `AUS` = "Australia",
                          `AUT` = "Austria",
                          `BELF` = "Belgium",
                          `BELW` = "Belgium",
                          `BRA` = "Brazilia",
                          `CAN` = "Canada",
                          `CHE` = "Switzerland",
                          `CHL` = "Chili",
                          `CRI` = "Costa Rica",
                          `DEU` = "Germany",
                          `DNK` = "Denkmark",
                          `FIN` = "Finland",
                          `FRA` = "France",
                          `GBR` = "Great Britain",
                          `GRC` = "Greece",
                          `HKG` = "Hong Kong",
                          `HUN` = "Hungary",
                          `IRL` = "Ireland",
                          `ISL` = "Iceland",
                          `ISR` = "Israel",
                          `ITA` = "Italy",
                          `JPN` = "Japan",
                          `KOR` = "Korea",
                          `LTU` = "Lithuania",
                          `MNE` = "Montenegro",
                          `NLD` = "the Netherlands",
                          `NOR` = "Norway",
                          `NZL` = "New Zealand",
                          `PRT` = "Portugal",
                          `SVK` = "Slovakia",
                          `SWE` = "Sweden",
                          `THA` = "Thailand",
                          `TUN` = "Tunesia",
                          `TUR` = "Turkey",
                          `TWN` = "Taiwan",
                          `URY` = "Uruguay",
                          `USA` = "United States"))

df <- d %>% 
  group_by(country) %>% 
  summarise(n = n(),
            trust = length(is.na(d$trust))/n,
            swd = length(is.na(d$swd))/n,
            wtac = length(is.na(d$wtac))/n,
            age = length(is.na(d$age))/n,
            gender = length(is.na(d$gender))/n,
            education = length(is.na(d$education))/n,
            income = length(is.na(d$income))/n,
            pid = length(is.na(d$pid))/n,
            political_interest = length(is.na(d$political_interest))/n,
            rile_selfplacement = length(is.na(d$rile_selfplacement))/n,
            gov_performance = length(is.na(d$gov_performance))/n) %>% 
  ungroup() %>% 
  select(-n, Country = country, `Political Trust` = trust,
  `Satisfaction with Democracy` = swd, `Willingness to Accept Compromise` = wtac,
  Age = age, Gender = gender, Education = education, Income = income,
  `Party Identification` = pid, `Political Interest` = political_interest,
  `Political Ideology` = rile_selfplacement, 
  `Evaluation of Government Performance` = gov_performance)

means <- d %>% 
  group_by(country) %>% 
  summarise(trust = round(mean(trust, na.rm = T),0),
            swd = round(mean(swd, na.rm = T),0),
            wtac = round(mean(wtac, na.rm = T),0),
            age = round(mean(age, na.rm = T),0),
            education = round(mean(education, na.rm = T),0),
            income = round(mean(income, na.rm = T),0),
            political_interest = round(mean(political_interest, na.rm = T),0),
            rile_selfplacement = round(mean(rile_selfplacement, na.rm = T),0),
            gov_performance = round(mean(gov_performance, na.rm = T),0),
            gender = round(mean(gender, na.rm = T),0),
            pid = round(mean(pid, na.rm = T),0)) 

countries <- means$country

for(i in 1:length(countries)){
  d <- d %>% 
    mutate(m_trust = ifelse(is.na(trust), 1, 0),
           trust = ifelse(country==countries[i] & is.na(trust), means$trust[means$country==countries[i]], trust),
           m_swd = ifelse(is.na(swd), 1, 0),
           swd = ifelse(country==countries[i] & is.na(swd), means$swd[means$country==countries[i]], swd),
           m_wtac = ifelse(is.na(wtac), 1, 0),
           wtac = ifelse(country==countries[i] & is.na(wtac), means$wtac[means$country==countries[i]], wtac),
           m_age = ifelse(is.na(age), 1, 0),
           age = ifelse(country==countries[i] & is.na(age), means$age[means$country==countries[i]], age),
           m_gender = ifelse(is.na(gender), 1, 0),
           gender = ifelse(country==countries[i] & is.na(gender), means$gender[means$country==countries[i]], gender),
           m_education = ifelse(is.na(education), 1, 0),
           education = ifelse(country==countries[i] & is.na(education), means$education[means$country==countries[i]], education),
           m_income = ifelse(is.na(income), 1, 0),
           income = ifelse(country==countries[i] & is.na(income), means$income[means$country==countries[i]], income),
           m_pid = ifelse(is.na(pid), 1, 0),
           pid = ifelse(country==countries[i] & is.na(pid), means$pid[means$country==countries[i]], pid),
           m_political_interest = ifelse(is.na(political_interest), 1, 0),
           political_interest = ifelse(country==countries[i] & is.na(political_interest), 
                                       means$political_interest[means$country==countries[i]], political_interest),
           m_rile_selfplacement = ifelse(is.na(rile_selfplacement), 1, 0),
           rile_selfplacement = ifelse(country==countries[i] & is.na(rile_selfplacement), 
                                       means$rile_selfplacement[means$country==countries[i]], rile_selfplacement),
           m_gov_performance = ifelse(is.na(gov_performance), 1, 0),
           gov_performance = ifelse(country==countries[i] & is.na(gov_performance), means$gov_performance[means$country==countries[i]], gov_performance))
}

d <- d %>% 
  mutate(pid = recode(pid, 
                      `0` = "No Partisan ID",
                      `1` = "Partisan ID"),
         gender = recode(gender, 
                         `1` = "Male",
                         `2` = "Female"))

