d <- d %>%
  mutate(D4 = recode(D4, 
                     `1` = "Big City",
                     `2` = "Suburb",
                     `3` = "Middlesized City",
                     `4` = "Rural Village",
                     `5` = "Countryside",
                     .default = "NA"), #6 participants DK
         D6 = recode(D6,
                     `1` = "CDU/CSU",
                     `2` = "SPD",
                     `3` = "AfD",
                     `4` = "FDP",
                     `5` = "Left",
                     `6` = "Greens",
                     `7` = "Other party", 
                     `8` = "Didn't vote/Not eligible",
                     .default = "NA"), #375 participants DK
         D7 = recode(D7, `12` = 0),  #DK = reference category
         D8 = recode(D8, `14` = 0), #DK = reference category
         D9 = recode(D9,
                     `1` = "Baden-Würtemberg",
                     `17` = "Bavaria",
                     `18` = "Berlin",
                     `19` = "Brandenburg",
                     `20` = "Bremen",
                     `21` = "Hamburg",
                     `22` = "Hessen",
                     `23` = "Lower Saxony",
                     `24` = "Mecklenburg-Western Pomerania",
                     `25` = "North Rhine-Westphalia",
                     `26` = "Rhineland-Palatinate",
                     `27` = "Saarland",
                     `28` = "Saxony",
                     `29` = "Saxony-Anholt",
                     `30` = "Schleswig-Holstein",
                     `31` = "Thuringia",
                     .default = "NA"), #2 particpants DK
         D10 = recode(D10,
                      `1` = "Baden-Würtemberg",
                      `17` = "Bavaria",
                      `18` = "Berlin",
                      `19` = "Brandenburg",
                      `20` = "Bremen",
                      `21` = "Hamburg",
                      `22` = "Hessen",
                      `23` = "Lower Saxony",
                      `24` = "Mecklenburg-Western Pomerania",
                      `25` = "North Rhine-Westphalia",
                      `26` = "Rhineland-Palatinate",
                      `27` = "Saarland",
                      `28` = "Saxony",
                      `29` = "Saxony-Anholt",
                      `30` = "Schleswig-Holstein",
                      `31` = "Thuringia",
                      `32` = "Not born in Germany", .default = "NA"), #5 participants DK
         PT1_1 = if_else(PT1_1 == 2, 0, 1),
         PT1_2 = if_else(PT1_2 == 2, 0, 1),
         PT1_3 = if_else(PT1_3 == 2, 0, 1),
         PT3_1 = if_else(PT3_1 <13, PT3_1 - 1, 0), # otherwise 1154 participants DK
         #PT3_1 = na_if(PT3_1, 13),
         PT3_2 = if_else(PT3_2 <13, PT3_2 - 1, 0), # otherwise 1263 participants DK
         #PT3_2 = na_if(PT3_2, 13),
         PT3_3 = if_else(PT3_3 <13, PT3_3 - 1, 0), # otherwise 983 participants DK
         #PT3_3 = na_if(PT3_3, 13),
         PT4 = if_else(PT4 == 3, 1, 0),
         PT5 = if_else(PT5 == 5, 1, 0),
         PT6 = if_else(PT6==1, 1, 0),
         PT7 =  na_if(PT7, 6), #48 participants
         S1 = recode(S1, 
                     `1` = "CDU",
                     `2` = "Greens",
                     `3` = "FDP",
                     `4` = "SPD"),
         MC1 = if_else(compromise == "yes" & MC1 == 1, 1,
               if_else(compromise == "no" & MC1 == 2, 1, 0)),
         MC2 = if_else(outcome == "negotiation" & MC2 == 1, 1,
               if_else(outcome == "stalled" & MC2 == 2, 1, 0)),
         MC3 = if_else(MC3 == "SPD, FDP, BÜNDNIS 90/DIE GRÜNEN", 1, 0),
         MC = MC1 + MC2,
         pol_know = PT4 + PT5 + PT6 + MC3,
         HT1a = round((HT1a_1 + HT1a_2 + HT1a_3 + HT1a_4 + HT1a_5 + HT1a_6)/6,0),
         HT1b_1 = 8 - HT1b_1,
         HT1b_2 = 8 - HT1b_2,
         HT1b_3 = 8 - HT1b_3,
         HT1b_4 = 8 - HT1b_4,
         HT1b_5 = 8 - HT1b_5,
         HT1b_6 = 8 - HT1b_6,
         HT1b = round((HT1b_1 + HT1b_2 + HT1b_3 + HT1b_4 + HT1b_5 + HT1b_6)/6,0),
         HT1 = HT1a + HT1b,
         HT2 = 5 - HT2,
         HT3 = round((HT3a + HT3b + HT3c)/3,0),
         POST = round((POST_1 + POST_2 + POST_3 + POST_4 + POST_5 + POST_6)/6),0) %>%
  select(id, D4:D10, PT1_1: PT3_3, pol_know, PT7:PT8, S1:S2, compromise, outcome,
         partner, issue, DV1:DV3, MC, HT1, HT2, HT3, POST) %>%
  drop_na()
